# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e537ccecce6b5efa8b65d086a06317a8ff7945771fc032346945b18394657022b25a96232cdce98d722f2b88e80e222a242ec17717f1c7963b6aa9217d251ff4

test:
  secret_key_base: e4393c150bab8bf4150217ff5fa6527fd4054ccf11603e6154a62158967f27efc1d1ee090fed8b76d3cee424de9c57aa994e95878226a3b802efe23e3604034a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
